### ISSUE TITLE
Resourcebundle loading problems for non existing bundles

### ISSUE THREAD

**Issue by 0verEngineer** [0verEngineer/InlineProblems#45]
Settings do not open for me on german windows

**Comment by 0verEngineer** [comment]
java.lang.NullPointerException: Cannot invoke "org.overengineer.inlineproblems.settings.SettingsComponent.isForceErrorsInSameLine()" because "this.settingsComponent" is null
                at org.overengineer.inlineproblems.settings.SettingsConfigurable.isModified(SettingsConfigurable.java:43)
                at com.intellij.openapi.options.ex.ConfigurableWrapper.isModified(ConfigurableWrapper.java:186)
                at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedInternal(SettingsEditor.java:524)
                at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedForItem(SettingsEditor.java:518)
                at com.intellij.openapi.options.newEditor.SettingsEditor.checkModified(SettingsEditor.java:506)
                at com.intellij.openapi.options.newEditor.SettingsEditor$5.updateCurrent(SettingsEditor.java:235)
                at com.intellij.openapi.options.newEditor.ConfigurableEditor.updateIfCurrent(ConfigurableEditor.java:237)
                at com.intellij.openapi.options.newEditor.ConfigurableEditor$4.run(ConfigurableEditor.java:194)
                at com.intellij.util.ui.update.Update.runUpdate(Update.java:114)
                at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:348)
                at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:338)
                at com.intellij.util.ui.update.MergingUpdateQueue.doFlush(MergingUpdateQueue.java:295)
                at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:274)
                at com.intellij.util.ui.EdtInvocationManager.invokeAndWaitIfNeeded(EdtInvocationManager.java:79)
                at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:274)
                at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
                at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:254)
                at com.intellij.util.Alarm$Request.runSafely(Alarm.java:373)
                at com.intellij.util.Alarm$Request.run(Alarm.java:360)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
                at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
                at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
                at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
                at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
                at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
                at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
                at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
                at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
                at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
                at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
                at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
                at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
                at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
                at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
                at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
                at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
                at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
                at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
                at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
                at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
                at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
                at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
                at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
                at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
                at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
                at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
                at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
                at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
                at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
                at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
                at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
                at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
                at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
                at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
                at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
                at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
                at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
                at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
                at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
                at java.desktop/java.awt.Dialog.lambda$show$2(Dialog.java:1081)
                at java.desktop/sun.awt.SunToolkit.performOnMainThreadIfNeeded(SunToolkit.java:2164)
                at java.desktop/java.awt.Dialog.show(Dialog.java:1041)
                at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:737)
                at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:462)
                at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)
                at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1643)
                at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.kt:104)
                at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:60)
                at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:47)
                at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
                at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
                at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$myActionProcessor$1.performAction(IdeKeyEventDispatcher.kt:502)
                at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$5$lambda$4(IdeKeyEventDispatcher.kt:865)
                at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
                at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
                at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$5(IdeKeyEventDispatcher.kt:865)
                at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
                at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner(IdeKeyEventDispatcher.kt:863)
                at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.access$doPerformActionInner(IdeKeyEventDispatcher.kt:1)
                at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction$intellij_platform_ide_impl(IdeKeyEventDispatcher.kt:587)
                at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:513)
                at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.kt:454)
                at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.kt:447)
                at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.kt:309)
                at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:617)
                at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:587)
                at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
                at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
                at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
                at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
                at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
                at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
                at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
                at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
                at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
                at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
                at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
                at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
                at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
                at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
                at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
                at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
                at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
                at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by 0verEngineer** [comment]
Fixed in c9cc381fb9114a071b509f004c7bcbb3505c22cf
